:sparkles: feat: add check for package-lock.json in CI/CD workflow for frontend

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -50,6 +50,12 @@ jobs:
           node-version: 20
           cache: "npm"
 
+      - name: Check for package-lock.json
+        run: |
+          if [ ! -f package-lock.json ]; then
+            echo "package-lock.json not found in $(pwd)" && exit 1
+          fi
+
       - name: Install dependencies
         run: npm ci
 
